### PR TITLE
Introduce unittests on rest v1

### PR DESCRIPTION
**Pull request by 4383**
Introduce some tests on:
- redfish_client
- HttpClient

### CODE REVIEW

**Comment by 4383** [comment]
I think you can now activate your travis account to trigger tests automatically on PR/merge/tags/etc...

**Comment by billdodd** [comment]
@4383 Thanks for the unit test contribution!

I did encounter an issue running with py27 (though with py36 it ran successfully):

```
✔ ~/Development/git/python-redfish-library [master|…1] 
12:29 $ tox -epy27
py27 develop-inst-noop: /Users/bdodd/Development/git/python-redfish-library
py27 installed: DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.,coverage==4.5.3,decorator==4.4.0,extras==1.0.0,fixtures==3.0.0,jsonpatch==1.23,jsonpath-rw==1.4.0,jsonpointer==2.0,linecache2==1.0.0,nose==1.3.7,nose-timer==0.7.5,pbr==5.2.0,ply==3.11,python-mimeparse==1.6.0,recordtype==1.3,-e git+git@github.com:billdodd/python-redfish-library.git@ae12fb0e5bc831c7fe22123b18cd78f86afd3650#egg=redfish,six==1.12.0,testtools==2.3.0,traceback2==1.4.0,unittest2==1.1.0,urlparse2==1.1.1
py27 run-test-pre: PYTHONHASHSEED='1077375761'
py27 runtests: commands[0] | nosetests --with-timer --with-coverage --cover-erase --cover-package=src
E
======================================================================
ERROR: Failure: ImportError (No module named src.redfish.rest.v1)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bdodd/Development/git/python-redfish-library/.tox/py27/lib/python2.7/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/bdodd/Development/git/python-redfish-library/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/bdodd/Development/git/python-redfish-library/.tox/py27/lib/python2.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/bdodd/Development/git/python-redfish-library/tests/test_redfish.py", line 4, in <module>
    from src.redfish.rest.v1 import redfish_client
ImportError: No module named src.redfish.rest.v1

Name                                 Stmts   Miss  Cover
--------------------------------------------------------
src/redfish/__init__.py                 15      7    53%
src/redfish/discovery/__init__.py        0      0   100%
src/redfish/discovery/discovery.py      36     27    25%
src/redfish/rest/__init__.py             1      0   100%
src/redfish/rest/v1.py                 451    344    24%
src/redfish/ris/__init__.py              5      0   100%
src/redfish/ris/config.py               73     57    22%
src/redfish/ris/ris.py                 327    271    17%
src/redfish/ris/rmc.py                 898    826     8%
src/redfish/ris/rmc_helper.py          286    186    35%
src/redfish/ris/sharedtypes.py          15      6    60%
--------------------------------------------------------
TOTAL                                 2107   1724    18%
[error] 100.00% nose.failure.Failure.runTest: 0.0001s
----------------------------------------------------------------------
Ran 1 test in 0.034s

FAILED (errors=1)
ERROR: InvocationError for command '/Users/bdodd/Development/git/python-redfish-library/.tox/py27/bin/nosetests --with-timer --with-coverage --cover-erase --cover-package=src' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   py27: commands failed
```

If I change the imports in test_redfish.py from this:

```
from src.redfish.rest.v1 import redfish_client
from src.redfish.rest.v1 import HttpClient
from src.redfish.rest.v1 import RetriesExhaustedError
```

to this:

```
from redfish.rest.v1 import redfish_client
from redfish.rest.v1 import HttpClient
from redfish.rest.v1 import RetriesExhaustedError
```

It then works on both py27 and py36. (Those are the only 2 python environments I currently have installed.)

**Comment by 4383** [comment]
@billdodd oh thanks good catch!

Fixed now!

**Comment by mraineri** [comment]
Approved 5/23

**Pull request merged**
