### PR TITLE
Added missing new line in M-SEARCH request

### LINKED ISSUE #142: rf_discover.py can not found AMI redfish server service
[rf_discover.py](url) can not found AMI redfish server service,

but another ssdp tool can found AMI redfish server service

python redfish libary version: 3.1.9
python redfish_utilities version: 3.1.5

run redfish's python version: 3.7.16
[log.txt](https://github.com/DMTF/Redfish-Tacklebox/files/12168303/log.txt)

run redfish's ssdp python version: 3.8.16

ssdp tool:
https://github.com/codingjoe/ssdp

ssdp tool version:
1.3.0

below is log
[log.txt](https://github.com/DMTF/Redfish-Tacklebox/files/12168306/log.txt)

### PR DESCRIPTION
**Pull request by mraineri**
Fix #142 

@PeterKchen2 would you be able to test this on your system for me? I don't have access to an AMI system and other systems are able to handle the missing newline in the request.

### CODE REVIEW

**Comment by mraineri** [comment]
Also needed another fix with the regex when inspecting the USN header.

**Comment by PeterKchen2** [comment]
OK

**Comment by PeterKchen2** [comment]
Dear mraineri

it work

Redfish services:
66ecf5de-bfde-11d3-01ea-819556480d00: https://192.168.199.7/redfish/v1/ (AMI Redfish Server)

**Comment by mraineri** [comment]
Awesome, thanks for testing.

Merging out of cycle to push out a bug fix.

**Pull request merged**
