### PR TITLE
if-match option support for PATCH/POST/PUT/DELETE method

### PR DESCRIPTION
**Pull request by PeterKchen2**
if-match option support for PATCH/POST/PUT/DELETE method

### CODE REVIEW

**Comment by mraineri** [comment]
A few things:

I'm a bit worried about blindly inserting ETags like this; I would expect this to be handled at a higher level. Effectively this gives the application the ability to simply ignore the existing state of a resource and force in a desired ETag. An application could do this already by inserting `If-Match: *` to tell the service that it doesn't matter what the current ETag is.

Redfish also does not dictate ETag usage for POST and DELETE; I would never expect ETags to be used in these cases.

I agree we need to solve this in rf_raw_request in Tacklebox though; I think it might be more appropriate to insert the header at that level.

**Comment by PeterKchen2** [comment]
3q for your feedback

**Comment by PeterKchen2** [comment]
according to your feedback, insert If-Match function should not implment in  python-redfish-library, should implment when higher level api need if-match/if-none-match??

and rf_raw_request script only need PATCH/PUT insert If-Match header

**Comment by mraineri** [comment]
> according to your feedback, insert If-Match function should not implment in python-redfish-library, should implment when higher level api need if-match/if-none-match??
> 
> and rf_raw_request script only need PATCH/PUT insert If-Match header

That's right; that's what I'm thinking currently.

**Pull request closed without merging**
